"""empty message

Revision ID: 43d5ffd82bf6
Revises: 
Create Date: 2020-05-18 08:33:45.636101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43d5ffd82bf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.add_column('accommodation', sa.Column('price', sa.Float(), nullable=False))
    op.alter_column('accommodation', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accommodation', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('accommodation', 'price')
    op.create_table('price',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('additional_guess_fee', mysql.FLOAT(), nullable=False),
    sa.Column('cleaning_fee', mysql.FLOAT(), nullable=False),
    sa.Column('security_fee', mysql.FLOAT(), nullable=False),
    sa.Column('monthly_price', mysql.FLOAT(), nullable=False),
    sa.Column('nightly_price', mysql.FLOAT(), nullable=False),
    sa.Column('weekend_price', mysql.FLOAT(), nullable=False),
    sa.Column('cancelation_policy', mysql.TEXT(), nullable=True),
    sa.Column('check_in', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('check_out', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
